/*
 * このソフトウエアはネクストデザイン有限会社に所有される機密情報です。
 * この機密情報を漏洩してはならず、当社の意図する許可の元において使用しなければなりません。
 * This software is confidential information owned by Next Design Ltd.
 * You must not disclose this confidential information and use it under the permission that we intend.
 * Copyright(c) 2015 NEXT DESIGN Ltd.
 */
package jp.co.nextdesign.ddb.core;

public class BdJpa {

	public String[] JPA_ANNOTATIONS = {
			"Annotation Types"
			, "Access"
			, "AssociationOverride" 
			, "AssociationOverrides" 
			, "AttributeOverride"
			, "AttributeOverrides" 
			, "Basic" 
			, "Cacheable" 
			, "CollectionTable" 
			, "Column" 
			, "ColumnResult" 
			, "DiscriminatorColumn" 
			, "DiscriminatorValue" 
			, "ElementCollection" 
			, "Embeddable" 
			, "Embedded" 
			, "EmbeddedId" 
			, "Entity" 
			, "EntityListeners" 
			, "EntityResult" 
			, "Enumerated" 
			, "ExcludeDefaultListeners" 
			, "ExcludeSuperclassListeners" 
			, "FieldResult" 
			, "GeneratedValue" 
			, "Id" 
			, "IdClass" 
			, "Inheritance" 
			, "JoinColumn" 
			, "JoinColumns" 
			, "JoinTable" 
			, "Lob" 
			, "ManyToMany" 
			, "ManyToOne" 
			, "MapKey" 
			, "MapKeyClass" 
			, "MapKeyColumn" 
			, "MapKeyEnumerated" 
			, "MapKeyJoinColumn" 
			, "MapKeyJoinColumns" 
			, "MapKeyTemporal" 
			, "MappedSuperclass" 
			, "MapsId" 
			, "NamedNativeQueries" 
			, "NamedNativeQuery" 
			, "NamedQueries" 
			, "NamedQuery" 
			, "OneToMany" 
			, "OneToOne" 
			, "OrderBy" 
			, "OrderColumn" 
			, "PersistenceContext" 
			, "PersistenceContexts" 
			, "PersistenceProperty" 
			, "PersistenceUnit" 
			, "PersistenceUnits" 
			, "PostLoad" 
			, "PostPersist" 
			, "PostRemove" 
			, "PostUpdate" 
			, "PrePersist" 
			, "PreRemove" 
			, "PreUpdate" 
			, "PrimaryKeyJoinColumn" 
			, "PrimaryKeyJoinColumns" 
			, "QueryHint" 
			, "SecondaryTable" 
			, "SecondaryTables" 
			, "SequenceGenerator" 
			, "SqlResultSetMapping" 
			, "SqlResultSetMappings" 
			, "Table" 
			, "TableGenerator" 
			, "Temporal" 
			, "Transient" 
			, "UniqueConstraint" 
			, "Version"
	};
}
